namespace Sanction.Loader.Core;

/// <summary>
/// Generated by tools/embed-loader-config.js — do not edit by hand.
/// Regenerate:  npm run loader:config [https://api.example.com]
///
///   api base   http://127.0.0.1:3000
///   key id     5e53b522757426b5
///   channel    stable
///   embedded   2026-09-13T18:46:02.898Z
/// </summary>
internal static class BuildConfig
{
    /// <summary>Base URL of the Sanction API, no trailing slash.</summary>
    public const string ApiBase = "http://127.0.0.1:3000";

    /// <summary>PEM (SPKI) of the server identity key — ECDSA P-256, id 5e53b522757426b5.</summary>
    public const string ServerPublicKeyPem = @"-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKAsHwiPGNbToFizqN5xH3jc5Q+WY
vf+zVJD7hkj8NoUI8wp+n6ydPBucniSqTgd2k+23j+UnF+FA10CgJFjbrA==
-----END PUBLIC KEY-----";

    /// <summary>Release channel reported to the server: stable | beta.</summary>
    public const string Channel = "stable";

    /// <summary>UTC timestamp of the configuration embed, for support requests.</summary>
    public const string ConfiguredAt = "2026-09-13T18:46:02.898Z";
}
